"""Second static pass: symbol imports, resource references, manifest classes, brace balance."""
import re, glob, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


APP = os.path.join(ROOT, 'app/src/main/kotlin/**/*.kt')
CORE = os.path.join(ROOT, 'core/src/main/kotlin/**/*.kt')
problems = []

def declared(pattern):
    found = {}
    for path in glob.glob(pattern, recursive=True):
        src = open(path).read()
        pkg = re.search(r'^package\s+([\w.]+)', src, re.M)
        pkg = pkg.group(1) if pkg else ''
        for m in re.finditer(r'\b(?:class|object|interface|typealias|enum class|data class|sealed interface|fun|val)\s+(?:\w+\.)?(\w+)', src):
            found.setdefault(f'{pkg}.{m.group(1)}', path)
    return found

symbols = {}
symbols.update(declared(APP))
symbols.update(declared(CORE))

# 1. project imports resolve
for path in glob.glob(APP, recursive=True) + glob.glob(CORE, recursive=True):
    for m in re.finditer(r'^import\s+(app\.paisa\.[\w.]+)', open(path).read(), re.M):
        ref = m.group(1)
        if ref == 'app.paisa.R':      # generated by the Android build
            continue
        if ref not in symbols and not any(k.startswith(ref + '.') for k in symbols):
            problems.append(f"{os.path.basename(path)}: import {ref} does not resolve")

# 2. brace / paren balance (catches a truncated file)
for path in glob.glob(APP, recursive=True) + glob.glob(CORE, recursive=True):
    src = open(path).read()
    src = re.sub(r'"""[\s\S]*?"""', '""', src)
    # char literals first: a Kotlin '"' would otherwise open a phantom string
    src = re.sub(r"'(\\.|[^'\\])'", "''", src)
    src = re.sub(r'"(\\.|[^"\\])*"', '""', src)
    src = re.sub(r'/\*[\s\S]*?\*/', ' ', src)
    src = re.sub(r'//[^\n]*', ' ', src)
    for open_ch, close_ch in (('{', '}'), ('(', ')'), ('[', ']')):
        if src.count(open_ch) != src.count(close_ch):
            problems.append(f"{os.path.basename(path)}: unbalanced {open_ch}{close_ch} "
                            f"({src.count(open_ch)} vs {src.count(close_ch)})")

# 3. R.* references exist in resources
res_names = set()
for path in glob.glob(os.path.join(ROOT, 'app/src/main/res/**/*.xml'), recursive=True):
    kind = os.path.basename(os.path.dirname(path)).split('-')[0]
    if kind in ('values',):
        for m in re.finditer(r'<(string|color|style)\s+name="([^"]+)"', open(path).read()):
            res_names.add(f'{m.group(1)}.{m.group(2)}')
    else:
        res_names.add(f'{kind}.{os.path.basename(path)[:-4]}')
for path in glob.glob(APP, recursive=True):
    for m in re.finditer(r'\bR\.(\w+)\.(\w+)', open(path).read()):
        key = f'{m.group(1)}.{m.group(2)}'
        if key not in res_names:
            problems.append(f"{os.path.basename(path)}: R.{key} is not defined in res/")

# 4. manifest class references exist
manifest = open(os.path.join(ROOT, 'app/src/main/AndroidManifest.xml')).read()
for m in re.finditer(r'android:name="(\.[\w.]+)"', manifest):
    cls = 'app.paisa' + m.group(1)
    if cls not in symbols:
        problems.append(f"AndroidManifest.xml: {cls} not found in sources")

# 5. manifest resource references
for m in re.finditer(r'"@(\w+)/(\w+)"', manifest):
    key = f'{m.group(1)}.{m.group(2)}'
    if m.group(1) in ('mipmap', 'xml', 'drawable', 'style', 'string') and key not in res_names:
        problems.append(f"AndroidManifest.xml: @{m.group(1)}/{m.group(2)} missing from res/")

print('\n'.join(problems) if problems else 'imports, resources, manifest and bracket balance all check out')
sys.exit(1 if problems else 0)
